### ISSUE TITLE
Create new Tuple ID (TID) Class

### ISSUE THREAD

**Issue by shanealv** [NMSUCS582Spring2018Group9/javaminibase#2]
Create a new tuple ID (`TID`) class with the following specifications (see the `RID` class):

## class TID
`global.TID` extends `java.lang.Object`
### Field Summary
``` java
int   numRIDs;
int   position;
RID[] recordIDs;
```
### Constructor Summary
``` java
TID(int numRIDs)
```
default constructor of class
``` java
TID(int numRIDs, int position)
```
constructor of class
``` java
TID(int numRIDs, int position, RID[] recordIDs)
```
constructor of class
### Method Summary
``` java
void copyTid(TID tid)
```
make a copy of the given tid1
``` java
boolean equals(TID tid)
```
Compares two TID objects
``` java
void writeToByteArray(byte[] array, int offset)
```
Write the tid into a byte array at offset
``` java
void setPosition(int position)
```
set the position attribute with the given value
``` java
void setRID(int column, RID recordID)
```
set the RID of the given column

**Comment by shanealv** [comment]
As noted in my commit, I'm uncertain about certain ways I handled things with this class.  See comments in the TID class (branch Issue 2) for notes

**Comment by aalbaltan** [comment]
Looks good.

**Comment by shanealv** [comment]
Testing Complete.  Merged to master, this should be done.
