### ISSUE TITLE
Establish the ColumnarFile Class

### ISSUE THREAD

**Issue by shanealv** [NMSUCS582Spring2018Group9/javaminibase#3]
Create a new class called `Columnarfile` (see the `heap.Heapfile` class for analogy):
``` java
package columnar.Columnarfile
class Columnarfile { ... }
```
### Field Summary
``` java 
static int numColumns
AttrType[] type
```
### Constructor Summary
``` java 
Columnarfile(java.lang.String name, int numColumns, AttrType[] type)
```
Initialize:  if columnar file does not exist, create one heapfile ("name.columnid") per column; also create a "name.hdr" file that contains relevant metadata.
### Method Summary
``` java 
void deleteColumnarFile()
```
Delete all relevant files from the database.
``` java 
TID insertTuple(byte[] tuplePtr)
```
Insert tuple into file, return its tid
``` java 
Tuple getTuple(TID tid)
```
Read the tuple with the given tid from the columnar file
``` java 
int getTupleCnt()
```
Return the number of tuples in the columnar file.
``` java 
TupleScan openTupleScan()
```
Initiate a sequential scan of tuples.
``` java 
Scan openColumnScan(int columnNo)
```
Initiate a sequential scan along a given column.
``` java 
boolean updateTuple(TID tid, Tuple newtuple)
```
Updates the specified record in the columnar file.
``` java 
boolean updateColumnofTuple(TID tid, Tuple newtuple, int column)
```
Updates the specified column of the specified record in the columnar file

**Comment by shanealv** [comment]
@Asb10 are you actively developing on this?  If not, I'll take over.  Other issues are blocked on this one.  Otherwise, if you've already got a non-functioning interface going for this class, get it posted so that the other issues aren't blocked.

**Comment by aalbaltan** [comment]
@shanealv yes, I am. I will post what I have.

**Comment by aalbaltan** [comment]
@shanealv @Cgood627 @Jbvaldez Columnarfile class is complete now. Some test cases can be found in CFTest.java file. More testing will be done once the batchinsert and query programs are done. If you have any questions or have found any bug please let me know. Check issue3 branch.
