### ISSUE TITLE
Establish the ColumnDB Class

### ISSUE THREAD

**Issue by shanealv** [NMSUCS582Spring2018Group9/javaminibase#5]
Create a new class called `ColumnDB` under `diskmgr` with the following specification (see `DB`):
``` java
package diskmgr
class ColumnDB { ... }
```
### Constructor Summary
``` java
ColumnDB()
```
default constructor

### Method Summary
same as the existing DB class (though implementations may differ)

**Comment by aalbaltan** [comment]
@shanealv @Jbvaldez @Cgood627 Can someone explain why do we need to create this class? The way I see it, Columnarfile class can rely on the existing DB class to manage pages on disk. Creating this class looks like an unnecessary redundancy.

**Comment by shanealv** [comment]
I imagine there will be slight functionality differences.  If not now, then later in phase 3.  At the very least, we are going to at least have it prepared for phase 2.
