### ISSUE TITLE
Establish the ColumnarFileScan Class

### ISSUE THREAD

**Issue by shanealv** [NMSUCS582Spring2018Group9/javaminibase#6]
Create a class `iterator.ColumnarFileScan` by modifying the class `iterator.FileScan`.
``` java
package iterator
class ColumnarFileScan { ... }
```
### Constructor Summary
``` java
ColumnarFileScan(java.lang.String file_name, AttrType[] in1, short[] s1_sizes, short len_in1, int n_out_flds, FldSpec[] proj_list, CondExpr[] outFilter)
```

### Method Summary
Methods are similar to `iterator.FileScan` though implementations may be different

**Comment by shanealv** [comment]
Blocked on Issue #3, need the ColumnarFile class established.

**Comment by shanealv** [comment]
Also blocked on Issue #4 for TupleScan

**Comment by shanealv** [comment]
@Asb10 whoa, leave some issues for us.  I was hoping to know get on more than one issue today. Mind if I finish up this one?

**Comment by aalbaltan** [comment]
@shanealv opsy, Yes sure man. Sorry I got lost in all the comments. I'm not very familiar with github. Anyways,  sure you can go ahead and work on this one. However, this issue cannot be done until I apply some changes to columnarfile.

**Comment by shanealv** [comment]
Gotcha, I'll finish this one up after I get your merge request reviewed

**Comment by aalbaltan** [comment]
@shanealv I was looking through some test files, and I discovered some inconsistencies of how tuples are used. Apparently, even some test files use tuples in a wrong way and that mislead me. I expect you will run into some troubles with row-based tables. I'm gonna apply a quick fix in the next hour.

**Comment by aalbaltan** [comment]
@shanealv I've integrated this into query program (issue #8), and it worked find. good job.
