### ISSUE TITLE
Implement "query"

### ISSUE THREAD

**Issue by shanealv** [NMSUCS582Spring2018Group9/javaminibase#8]
Implement a program `query`. Given the command line invocation:
``` bash
query DBNAME VALUECONSTRAINT NUMBUF
```
the program will access the database and print out the matching results.   

The `VALUECONSTRAINT` is of the form `"COLUMNNAME OPERATOR VALUE"`.  

Minibase will use at most `NUMBUF` buffer pages to run the query (see the class `BufMgr`).  

If `DBNAME` was created using the type `column`, then the query should be executed in a column-oriented manner.  

At the end of the query, the program should output the number of disk pages that were read and the number of disk pages that were written (if any).

**Comment by shanealv** [comment]
@Jbvaldez  Skeleton for ColumnarFileScan if ready to go from the [issue 6 branch](/NMSUCS582Spring2018Group9/javaminibase/tree/6-columnarfilescan).  See the referenced commit for details.

You should probably merge this branch into your working branch or make a new branch off of the issue 6 one for your code at some point.

**Comment by aalbaltan** [comment]
@shanealv done.
