### ISSUE TITLE
Update Makefiles use of Absolute Paths

### ISSUE THREAD

**Issue by shanealv** [NMSUCS582Spring2018Group9/javaminibase#9]
As noted by @Asb10, the makefiles use absolute paths that aren't portable.  Either these need to be made relative, or we all use our own version of the makefile (easier, not ideal).

**Comment by aalbaltan** [comment]
I've updated the absolute paths. All paths are relative now. Don't forget to set JAVA_HOME env. variable. Building works find on my machine. We need 1 more to test it and make sure it works on his machine before merging with master.

**Comment by shanealv** [comment]
I gave it a quick test on my VM.  No issues popped up on my end using the new branch
